# Copyright (c) 2023 Contextual AI, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.
"""
Contains the functions for loading data.
Each function of the form get_{dataset_name} (e.g., get_shp, get_oasst, etc.) will return a dict of Example objects, indexed by the prompt for the text.

Each Example object will contain
- the prompt
- a list L of generations
- the index in L of the generation that should be the finetuning target
- a list S of the scores for the generations
- for preference feedback data: pairs of indices (i,j) in L, where generation i is preferable to generation j
- for binary feedback data: whether each generation is desirable/chosen or undesirable/rejected
- whether to truncate the beginning or end if the maximum number of tokens is exceeded
- the dataset name
- the unformatted prompt
"""

import datasets
import torch
from torch.nn.utils.rnn import pad_sequence
from collections import defaultdict
import tqdm
import re
import random
import json
from typing import Dict, List, Optional, Tuple
from dataclasses import dataclass, field
from .utils import rank0_print, on_rank0, delete_dict
import pandas as pd
import numpy as np

@dataclass
class Example:
    """
    Class for an example in a preference or SFT dataset. If you want each prompt to be uniquely associated with an Example instance, save it in a dict.
    """
    prompt: List = field(default_factory=list)                  # list of turns, each with two keys: "role" and "content"
    generations: List = field(default_factory=list)             # list of list of turns (the output sequences to predict)
    sft_index: int = -1                                         # which response in self.generations should be generated for SFT
    scores: List[float] = field(default_factory=list)           # score for each generation
    pairs: List[Tuple[int, int]] = field(default_factory=list)  # for preference feedback data: indices in responses, where i > j in pair (i,j) is a preference
    desirable: List[bool] = field(default_factory=list)         # for binary feedback data: whether the generation at the corresponding index in self.generations is desirable 
    truncation_mode: str = 'keep_end'                           # if truncation needed, keep the beginning (keep_start) or end (keep_end) (only override default for SHP)
    dataset_name: str = ''
    original_prompt: str = ''                                   # the unformatted prompt (needed to recover instruction for AlpacaEval)
    answer: str = ''                                            # ground truth answer for math-problem solving
    advantage: float = 0.0                                      # Advantage value

    def num_generations(self):
        return len(self.generations)
    
    def remove_extra_spaces(self):
        """
        Remove double spaces in the prompt and generations to standardize spacing.
        """
        def clean(text: str) -> str:
            return re.sub(r'[ \t]{2,}', ' ', text)

        # Clean the prompt
        for turn in self.prompt:
            turn['content'] = clean(turn['content'])

        # Clean the generations
        for x in self.generations:
            for turn in x:
                turn["content"] = clean(turn["content"])


class Dataset:
    """
    A collection of Example instances, indexed by prompt.
    """
    def __init__(self, name):
        self.name = name
        self.data = defaultdict(Example)

    def __setitem__(self, key, value):
        if not isinstance(key, str):
            raise KeyError("key must be a string")
        
        if not isinstance(value, Example):
            raise ValueError("value must be a Example")
        
        self.data[key] = value

    def __getitem__(self, key):
        return self.data[key]

    def __len__(self):
        return len(self.data)
    
    def __iter__(self):
        return iter(self.data)



def get_sampled_data(samples_path: str, split: str) -> Dataset:
    """
    Load samples generated by train.sample and convert it into a Dataset.
    """
    rank0_print(f'Loading samples from {samples_path}...')

    # Load all sample data
    with open(samples_path, 'r') as f:
        sample_data = json.load(f)

    data = Dataset('samples')

    for sample in sample_data:
        if sample.get('split', split) != split:
            continue

        prompt_key = str(sample['prompt_id']) + ' ' + str(sample['sample_id'])
        data[prompt_key].prompt = sample['prompt']
        data[prompt_key].generations.append([{"role": "assistant", "content": sample['output']}])
        data[prompt_key].dataset_name = sample['dataset']
        data[prompt_key].sft_index = 0

    return data    


def get_feedback(feedback_path: str, split: str) -> Dataset:
    """
    Load feedback data created by label.py and convert it into a Dataset.
    Supports both binary and pairwise feedback formats.

    Args:
        feedback_path: path to the JSON file containing feedback data
        split: only include objects whose 'split' value matches the given split

    Returns:
        A Dataset instance containing the feedback data.
    """
    rank0_print(f'Loading feedback dataset from {feedback_path}...')
    
    # Load all feedback data
    with open(feedback_path, 'r') as f:
        feedback_data = json.load(f)
    
    if not feedback_data:
        raise ValueError(f"No feedback data found in {feedback_path}")
    
    data = Dataset('feedback')

    # Group samples by flattened prompt to ensure we handle all samples for each prompt together
    grouped_samples = defaultdict(list)
    for item in feedback_data:
        prompt_key = ' '.join([ x['content'] for x in item['prompt'] ]) # flattened prompt
        grouped_samples[prompt_key].append(item)
    
    for prompt_key, samples in grouped_samples.items():
        if not samples: continue

        feedback_type = samples[0].get('type', None)   
        if not feedback_type:
            raise ValueError("Feedback type not specified in data") 
        
        # split is same for all examples with the same prompt
        if samples[0].get('split', split) != split:
            continue
        
        if feedback_type == 'binary_feedback':
            example = Example()
            
            # Add each sample's output and its desirability based on the label
            for sample in samples:
                example.prompt = sample['prompt']
                example.generations.append(sample['output'])
                example.desirable.append(bool(sample['label']))
                example.scores.append(sample['reward'])
                example.dataset_name = 'feedback'
                if "advantage" in sample.keys():
                    example.advantage = sample['advantage']
            
            # For binary feedback, use any desirable response as the SFT target
            # If no desirable responses, use the highest scoring one
            desirable_indices = [i for i, d in enumerate(example.desirable) if d]
            if desirable_indices:
                example.sft_index = desirable_indices[0]
            else:
                example.sft_index = max(range(len(example.scores)), key=lambda i: example.scores[i])

            data[prompt_key] = example
            
        elif feedback_type == 'pairwise_feedback':
            example = Example()
            
            # Track unique outputs to avoid duplicates
            output_to_idx = {}
            
            for pair in samples:
                example.prompt = pair['prompt']
                example.dataset_name = 'feedback'

                # Add outputs if not already added
                if pair['output_A'][0]['content'] not in output_to_idx:
                    output_to_idx[pair['output_A'][0]['content']] = len(example.generations)
                    example.generations.append(pair['output_A'])
                    example.scores.append(pair['reward_A'])
                    
                if pair['output_B'][0]['content'] not in output_to_idx:
                    output_to_idx[pair['output_B'][0]['content']] = len(example.generations)
                    example.generations.append(pair['output_B'])
                    example.scores.append(pair['reward_B'])
                
                # Add preference pair as a tuple of indices
                if pair['label'] == 1:
                    example.pairs.append((output_to_idx[pair['output_A'][0]['content']], output_to_idx[pair['output_B'][0]['content']]))
                else:
                    example.pairs.append((output_to_idx[pair['output_B'][0]['content']], output_to_idx[pair['output_A'][0]['content']]))
            
            # Use highest scoring response as SFT target
            example.sft_index = max(range(len(example.scores)), key=lambda i: example.scores[i])
            
            data[prompt_key] = example
        else:
            raise ValueError(f"Unsupported feedback type: {feedback_type}")
    
    return data

def get_math500(split: str = "test") -> Dataset:
    """
    Load the HuggingFaceH4/MATH-500 dataset and convert it into a Dataset.
    
    Args:
        split: one of 'test', 'train' (default: 'test')
        
    Returns:
        A Dataset instance containing MATH-500 problems.
    """
    
    rank0_print(f'Loading MATH-500 dataset ({split} split) from Huggingface...')
    
    # Load the dataset
    dataset = datasets.load_dataset("HuggingFaceH4/MATH-500", split=split)
    data = Dataset('MATH-500')
    
    if on_rank0():
        dataset = tqdm.tqdm(dataset, desc='Processing MATH-500')
    
    for row in dataset:
        problem = row['problem']
        solution = row['solution']
        answer = row['answer']
        
        # Create a conversation format with the problem as the human prompt
        conversation = [
            {"role": "user", "content": problem}
        ]
        
        # Use the problem as the key
        data[problem].prompt = conversation
        
        # Add the solution and answer as the assistant's response
        response = f"Solution:\n{solution}\n\nAnswer: {answer}"
        data[problem].generations.append([{"role": "assistant", "content": response}])
        data[problem].answer = answer
        # Set this as the preferred response (for SFT)
        data[problem].sft_index = 0    
    return data


def get_hendrycks_math(split: str = "train", subsets: Optional[List[str]] = None) -> "Dataset":
    """
    Load the EleutherAI/hendrycks_math dataset and convert it into a Dataset.
    
    Args:
        split: one of 'test', 'train' (default: 'test')
        subsets: list of math subsets to load, defaults to all subsets if None
        
    Returns:
        A Dataset instance containing math problems from specified subsets.
    """
    from train.math_parsingutil import extract_answer
    
    # All available subsets
    all_subsets = [
        "algebra", 
        "counting_and_probability", 
        "geometry", 
        "intermediate_algebra", 
        "number_theory", 
        "prealgebra", 
        "precalculus"
    ]
    
    # Use all subsets if none specified
    if subsets is None:
        subsets = all_subsets
    
    print(f'Loading hendrycks_math dataset ({split} split) with subsets: {", ".join(subsets)}')
    
    # Create empty dataset to hold the results
    data = Dataset('hendrycks_math')
    
    # Process each subset
    for subset in subsets:
        print(f'Processing subset: {subset}')
        
        # Load the dataset for this subset
        dataset = datasets.load_dataset("EleutherAI/hendrycks_math", subset, split=split)
        
        # Process each example
        for row in tqdm.tqdm(dataset, desc=f'Processing {subset}'):
            problem = row['problem']
            solution = row['solution']
            
            # Extract answer from \boxed{} in the solution
            answer = extract_answer(solution)
            
            # Skip examples where we couldn't extract an answer
            if answer is None:
                print(f"Warning: Could not extract answer from solution for problem: {problem[:50]}...")
                continue
            
            # Create a conversation format with the problem as the human prompt
            conversation = [
                {"role": "user", "content": problem}
            ]
            
            # Use a unique identifier as the key
            key = f"{subset}_{row['id']}" if 'id' in row else f"{subset}_{hash(problem) % 10000}"
            
            # Store the problem, solution, and extracted answer
            data[key].prompt = conversation
            
            # Add the solution and answer as the assistant's response
            response = f"Solution:\n{solution}\n\nAnswer: {answer}"
            data[key].generations.append([{"role": "assistant", "content": response}])
            data[key].answer = answer
            
            # Set this as the preferred response (for SFT)
            data[key].sft_index = 0
    
    print(f'Processed {len(data)} total examples across {len(subsets)} subsets')
    return data

class DataLoader:
    """
    The base data loader class, similar to the one from the DPO repo.
    Subclass this and overwrite the __iter__ method as needed, since the batcch elements will be different depending
    on whether you're doing SFT, aligning with a pairwise loss like DPO, or alignment with an unpaired loss like KTO. 
    """
    def __init__(self, 
                 dataset_names: List[str],
                 tokenizer,
                 process_index: int = 0,
                 num_processes: int = 1,
                 split: str = 'train',
                 microbatch_size: int = 1,
                 max_length: int = 512,
                 max_prompt_length: int = 128,
                 max_prompt_count: int = None,
                 n_epochs: Optional[int] = None,
                 n_examples: Optional[int] = None,
                 seed: int = 0,
                 control_tokens: Dict = {},
                 **kwargs):
        
        torch.manual_seed(seed)
        self.rng = random.Random(seed)
        self.tokenizer = tokenizer
        self.process_index = process_index
        self.num_processes = num_processes
        self.control_tokens = control_tokens
        self.split = split
        self.microbatch_size = microbatch_size
        self.max_length = max_length
        self.max_prompt_length = max_prompt_length
        self.max_prompt_count = max_prompt_count
        self.kwargs = kwargs

        assert n_epochs is not None or n_examples is not None, "Must specify either n_epochs or n_examples"
        self.n_epochs = n_epochs
        self.epoch_idx = 0
        self.n_examples = n_examples
        
        self.full_data = {} # a dict of Examples

        for name in dataset_names:
            if f"get_{name}" in globals():
                dataset = globals()[f"get_{name}"](split)
                self.full_data.update(dataset.data)
            else:
                try:
                    with open(name, 'r') as f:
                        data = json.load(f)

                        if data[0]['type'] == 'sample':
                            dataset = get_sampled_data(name, split)
                        elif data[0]['type'].endswith('feedback'):
                            dataset = get_feedback(name, split)
                        else:
                            raise IOError("unrecognized data type")
                        
                        self.full_data.update(dataset.data)
                except:
                    raise IOError(f"could not load {name}")

        self.num_training_steps = self.get_num_training_steps()

    def collate(self, batch: Dict[str, List]) -> Dict:
        """
        Takes a list of examples and returns a batch of examples with consistent padding across all processes.
        Uses a fixed maximum length for padding to ensure consistency across batches and processes.
        """
        if self.tokenizer.pad_token_id is None:
            raise Exception("tokenizer's pad_token_id is not specified")
        
        padded_batch = {}
        for k in batch[0].keys():
            if k.endswith('_input_ids') or k.endswith('_attention_mask') or k.endswith('_labels'):
                if 'prompt' in k:
                    # flip prompt so that you are padding to the beginning
                    to_pad = [torch.LongTensor(ex[k][::-1]) for ex in batch]
                else:
                    to_pad = [torch.LongTensor(ex[k]) for ex in batch]

                if k.endswith('_input_ids'):
                    padding_value = self.tokenizer.pad_token_id
                elif k.endswith('_labels'):
                    padding_value = -100
                elif k.endswith('_attention_mask'):
                    padding_value = 0
                else:
                    raise ValueError(f"Unexpected key in batch '{k}'")

                # Always pad to max_length for consistency across processes
                max_len = self.max_prompt_length if 'prompt' in k else self.max_length

                padded_sequences = []
                for seq in to_pad:
                    if len(seq) > max_len:
                        padded_seq = seq[:max_len]
                    else:
                        padding_size = max_len - len(seq)
                        padding = torch.full((padding_size,), padding_value, dtype=seq.dtype)
                        padded_seq = torch.cat([seq, padding])
                    padded_sequences.append(padded_seq)

                padded_batch[k] = torch.stack(padded_sequences)
                if 'prompt' in k:
                    padded_batch[k] = padded_batch[k].flip(dims=[1])
            elif k == "answer":
                padded_batch[k] = [ex[k] for ex in batch]
            else:
                padded_batch[k] = [ex[k] for ex in batch]

        return padded_batch

    def tokenize_batch_element(self, conversation: List[Dict[str, str]], generation: str, truncation_mode: str, prefix: str='target') -> Dict:
        """
        Tokenize a single batch element and truncate if prompt + generation is too long. Batch element is turned into Pytorch 
        tensors in self.collate. Create the labels for the generation, which are of length equal to the sum of the length of 
        the prompt and the generation, with -100 for the prompt tokens.

        Args:
        - conversation: list of previous turns, each resembling dict {"role": "assistant", "content": generation}
        - generation: list of current turns, each resembling dict {"role": "assistant", "content": generation}
        - truncation_mode: one of 'keep_start'/'keep_end' (truncate end/beginning of prompt respectively)
        - prefix: the prefix corresponding to the generation (e.g., 'chosen', 'rejected', 'target')

        Returns:
            A dict of the tokenized prompt and the concatenation of the two on all relevant elements (e.g., tokens, 
            attention mask, etc.). The generation elements will have keys starting with '{prefix}_' and the concatenated 
            elements will have keys starting with '{prefix}_combined_'. 'prompt' will map to the raw conversation history,
            as a list of dicts, and the prefix key alone will map to the untemplated output.
        """
        untruncated_prompt_string = self.tokenizer.apply_chat_template(conversation, tokenize=False, add_generation_prompt=True) # for inference-time generation
        
        filter_out_bos_eos = lambda x: [ t for t in x if t not in [ self.tokenizer.bos_token_id, self.tokenizer.eos_token_id, self.tokenizer.pad_token_id] ]
        # truncate the prompt if necessary
        total_length = 0

        # truncate history to fit in self.max_prompt_length
        for i, turn in enumerate(conversation):
            content_token_ids = filter_out_bos_eos(self.tokenizer.encode(turn['content']))
            # we're only modifying the text in content but need to consider the formatted length
            templated_length = len(self.tokenizer.apply_chat_template([turn], tokenize=True, add_generation_prompt=True))
            
            if total_length + templated_length > self.max_prompt_length:
                turn['content'] = self.tokenizer.decode(content_token_ids[:self.max_prompt_length - (total_length + templated_length)])
                total_length = self.max_prompt_length
                break
            else:
                total_length += templated_length

        conversation = conversation[:(i+1)]

        # truncate the generation if necessary 
        for i, turn in enumerate(generation):
            content_token_ids = filter_out_bos_eos(self.tokenizer.encode(turn['content']))
            # we're only modifying the text in content but need to consider the formatted length
            templated_length = len(self.tokenizer.apply_chat_template([turn], tokenize=True, add_generation_prompt=False))
            
            if total_length + templated_length > self.max_length:
                turn['content'] = self.tokenizer.decode(content_token_ids[:self.max_length - (total_length + templated_length)])
                total_length = self.max_length
                break
            else:
                total_length += templated_length

        generation = generation[:(i+1)]

        tokenized_prompt = self.tokenizer.apply_chat_template(conversation, tokenize=True, add_generation_prompt=True)
        tokenized_prompt_and_generation_string = self.tokenizer.apply_chat_template(conversation + generation, tokenize=False, add_generation_prompt=False)
        tokenized_prompt_and_generation = self.tokenizer.apply_chat_template(
            conversation + generation, 
            tokenize=True, 
            add_generation_prompt=False
        )

        # Prepare the batch element
        batch_element = {
            'prompt': conversation,
            f'{prefix}': generation,
            'prompt_text': untruncated_prompt_string,
            'prompt_input_ids': tokenized_prompt,
            f'{prefix}_text': self.tokenizer.apply_chat_template(generation, tokenize=False),
            f'{prefix}_combined_text': tokenized_prompt_and_generation_string,
            f'{prefix}_combined_input_ids': tokenized_prompt_and_generation,
            f'{prefix}_combined_attention_mask': [1] * len(tokenized_prompt_and_generation),
        }

        # Prepare labels
        tokenized_prompt = self.tokenizer.apply_chat_template(conversation, tokenize=True, add_generation_prompt=True)
        if tokenized_prompt[-1] in [self.tokenizer.eos_token_id, self.tokenizer.pad_token_id]:
            tokenized_prompt.pop()
        
        labels = tokenized_prompt_and_generation[:]
        labels[:len(tokenized_prompt)] = [-100] * len(tokenized_prompt)
        batch_element[f'{prefix}_labels'] = labels

        return batch_element

    def __iter__(self):
        """Create a flat version of the data and yield batches."""
        raise NotImplementedError

    def get_num_training_steps(self):
        """Get the number of training steps."""
        raise NotImplementedError
    

class SFTDataLoader(DataLoader):
    """
    Dataloader for supervised fine-tuning.
    """
    def __iter__(self):
        flat_data = []
        prompts = list(self.full_data.keys())
        
        for prompt in prompts:
            flat_data.append(self.full_data[prompt])

        if self.num_processes == 1: # for eval usually
            usable_size = len(flat_data)
        else: # to avoid hanging with uneven batches
            global_batch_size = int(self.num_processes * self.microbatch_size)
            usable_size = len(flat_data) // global_batch_size * global_batch_size
        
        self.rng.shuffle(flat_data)
        flat_data = [d for i, d in enumerate(flat_data[:usable_size]) if i % self.num_processes == self.process_index]

        epoch_idx = 0
        example_idx = 0
        done = False
        
        while True:
            if done: break
            self.rng.shuffle(flat_data)

            batch = []

            for example in flat_data:
                # Assuming example.prompt is now a list of conversation turns
                conversation = example.prompt
                if not isinstance(conversation[0], dict):
                    # Convert to the new format if it's not already
                    conversation = [{"role": "user", "content": conversation[0]}]
                    for i, message in enumerate(conversation[1:]):
                        role = "assistant" if i % 2 == 0 else "user"
                        conversation.append({"role": role, "content": message})

                # Get the target generation (last turn from assistant)
                target_generation = example.generations[example.sft_index]

                # Add control token if specified
                if self.control_tokens.get('chosen'):
                    target_generation = self.control_tokens['chosen'] + target_generation

                batch_element = self.tokenize_batch_element(
                    conversation,
                    target_generation,
                    example.truncation_mode
                )
                batch_element['original_prompt'] = example.original_prompt
                #for gt_answer tracking
                batch_element['answer'] = example.answer
                batch.append(batch_element)

                if len(batch) == self.microbatch_size:
                    example_idx += len(batch) * self.num_processes
                    yield self.collate(batch)
                    batch = []

                    if self.n_examples is not None and example_idx >= self.n_examples:
                        rank0_print(f'Finished generating {self.n_examples} examples on {self.split} split')
                        done = True
                        break

            if self.num_processes == 1 and batch != []: # flush for eval, sampling
                yield self.collate(batch) 
                batch = []

            epoch_idx += 1
            if self.n_epochs is not None and epoch_idx >= self.n_epochs:
                done = True
                break

    def get_num_training_steps(self):
        """Get the number of training steps."""
        return len(self.full_data) // self.num_processes


class ConditionalSFTDataLoader(DataLoader):
    """
    Dataloader for token-conditioned SFT, in the style of Korbak et al.'s (2023) "Pretraining Models with Human
    Feedback."

    For training, each output is prepended with a control token denoting whether it's desirable or undesirable
    (<|good|> or <|bad|> respectively). For sampling, each input is postpended with the <good> token to ensure
    that only desirable outputs are generated.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.control_tokens.get('chosen') is None:
            raise KeyError("control token for chosen outputs not specified")
        
        if self.control_tokens.get('rejected') is None:
            raise KeyError("control token for rejected outputs not specified")

    def get_flat_data(self, prompts):
        """
        Return a flat list of examples given a list of prompts that index self.full_data.
        Prepend the examples with the appropriate control tokens.
        """
        flat_data = []

        for prompt in prompts:
            example = self.full_data[prompt]

            if self.max_prompt_count:
                example.pairs = self.rng.sample(example.pairs, min(self.max_prompt_count, len(example.pairs)))

            for i,j in example.pairs:
                flat_data.append((example, example.generations[i], 'chosen'))
                flat_data.append((example, example.generations[j], 'rejected'))

        return flat_data
    
    def __iter__(self):
        prompts = list(self.full_data.keys())
        flat_data = self.get_flat_data(prompts)

        if self.num_processes == 1: # for eval usually
            usable_size = len(flat_data)
        else: # to avoid hanging with uneven batches
            global_batch_size = int(self.num_processes * self.microbatch_size)
            usable_size = len(flat_data) // global_batch_size * global_batch_size
        
        self.rng.shuffle(flat_data) # shuffle before splitting across processes, otherwise some processes will only get chosen examples
        flat_data = [d for i, d in enumerate(flat_data[:usable_size]) if i % self.num_processes == self.process_index]
      
        epoch_idx = 0
        example_idx = 0
        done = False
        
        while True:
            if done: break
            self.rng.shuffle(flat_data)

            batch = []

            for example, generation, status in flat_data:
                # Convert prompt to conversation format if it's not already
                conversation = example.prompt
                if not isinstance(conversation[0], dict):
                    conversation = [{"role": "user", "content": conversation[0]}]
                    for i, message in enumerate(conversation[1:]):
                        role = "assistant" if i % 2 == 0 else "user"
                        conversation.append({"role": role, "content": message})

                # Add control token to the generation
                if status == 'chosen':
                    conditioned_generation = self.control_tokens["chosen"] + generation
                else:
                    conditioned_generation = self.control_tokens["rejected"] + generation

                batch_element = self.tokenize_batch_element(
                    conversation,
                    conditioned_generation,
                    example.truncation_mode
                )
                batch_element['status'] = status
                batch.append(batch_element)

                if len(batch) >= self.microbatch_size:
                    example_idx += len(batch) * self.num_processes
                    yield self.collate(batch)
                    batch = []

                    if self.n_examples is not None and example_idx >= self.n_examples:
                        rank0_print(f'Finished generating {example_idx} examples on {self.split} split')
                        done = True
                        break

            if self.num_processes == 1 and batch != []: # flush for eval, sampling
                yield self.collate(batch)
                batch = []

            epoch_idx += 1
            if self.n_epochs is not None and epoch_idx >= self.n_epochs:
                done = True
                break

    def get_num_training_steps(self):
        max_prompt_count = min(float("inf"), self.max_prompt_count) if self.max_prompt_count else float("inf")
        num_pairs = int(sum(min(max_prompt_count, len(example.pairs)) for _, example in self.full_data.items()))
        num_training_steps = num_pairs * 2
        return num_training_steps // self.num_processes


class UnpairedPreferenceDataLoader(DataLoader):
    """
    Dataloader for losses that do not require pairwise preferences (e.g., KTO).

    This assumes that if an example has no pairs, then it is naturally unpaired, using the 'desirable' field
    to infer its label. If an example has pairs, then it is assumed to be from a naturally paired dataset, and 
    the preferred/dispreferred generations are from the desirable/undesirable conditional generations given x. 
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.microbatch_size * self.num_processes <= 1:
            raise ValueError("can't use batch size of 1 with UnpairedPreferenceDataLoader")
        
    def get_flat_data(self, prompts):
        """
        Return a flat list of examples given a list of prompts that index self.full_data.
        """
        if self.max_prompt_count:
            num_unique = sum(min(self.max_prompt_count, len(self.full_data[prompt].generations)) for prompt in prompts)
        else:
            num_unique = sum(len(self.full_data[prompt].generations) for prompt in prompts)

        allowed_desirable = num_unique * self.kwargs.get('frac_unique_desirable', np.inf)
        allowed_undesirable = num_unique * self.kwargs.get('frac_unique_undesirable', np.inf)
        seen_desirable = 0
        seen_undesirable = 0

        flat_data = []

        for prompt in prompts:
            example = self.full_data[prompt]

            # naturally unpaired feedback
            if example.pairs == [] and example.desirable != []:
                for i in range(len(example.desirable)):
                    if seen_desirable < allowed_desirable and example.desirable[i]:
                        flat_data.append((example, example.generations[i], 'chosen'))
                        seen_desirable += 1

                    if seen_undesirable < allowed_undesirable and not example.desirable[i]:
                        flat_data.append((example, example.generations[i], 'rejected'))
                        seen_undesirable += 1
            # getting unpaired data out of pairs
            elif example.pairs != []:
                if self.max_prompt_count:
                    example.pairs = self.rng.sample(example.pairs, min(self.max_prompt_count, len(example.pairs)))

                for i,j in example.pairs:
                    if seen_desirable < allowed_desirable:
                        flat_data.append((example, example.generations[i], 'chosen'))
                        seen_desirable += 1
                    
                    if seen_undesirable < allowed_undesirable:
                        flat_data.append((example, example.generations[j], 'rejected'))
                        seen_undesirable += 1
            else:
                raise IOError("data is neither paired nor has desirability labels")

        return flat_data

    def __iter__(self):
        prompts = list(self.full_data.keys())
        flat_data = self.get_flat_data(prompts)

        if self.num_processes == 1: # for eval usually
            usable_size = len(flat_data)
        else: # to avoid hanging with uneven batches
            global_batch_size = int(self.num_processes * self.microbatch_size)
            usable_size = len(flat_data) // global_batch_size * global_batch_size
        
        self.rng.shuffle(flat_data) # shuffle before splitting across processes, otherwise some processes will only get chosen examples
        flat_data = [d for i, d in enumerate(flat_data[:usable_size]) if i % self.num_processes == self.process_index]

        epoch_idx = 0
        example_idx = 0
        done = False

        while True:
            if done: break
            self.rng.shuffle(flat_data)   # so generations in the same preference are not in the same batch
            batch = []
            example_queue = []

            for example, generation, status in flat_data:
                batch_element = self.tokenize_batch_element(example.prompt, generation, example.truncation_mode, prefix='target')
                batch_element['status'] = status 
                batch_element['truncation_mode'] = example.truncation_mode
                batch_element['conversation'] = example.prompt
                batch_element['generation'] = generation
                example_queue.append(batch_element)
                
                if len(example_queue) >= self.microbatch_size:
                    while len(batch) < self.microbatch_size:
                        batch.append(example_queue.pop(0))
                    
                if len(batch) >= self.microbatch_size:
                    # for estimating the KL term, match up x and y' that are not corresponding input-output pairs in the data
                    # for x_i, get a mismatched y' by just picking the subsequent y_{i+1} in the batch (desirable/undesirable status does not matter)
                    # the respective input IDs, attention mask, and so on will be prefixed by the term KL
                    indices = list(range(1, len(batch))) + [0]
                    for i in range(len(batch)):
                        batch[i].update(self.tokenize_batch_element(
                            batch[i]['conversation'],
                            batch[indices[i]]['generation'],
                            batch[i]['truncation_mode'],
                            prefix='KL'
                        ))

                    example_idx += len(batch) * self.num_processes
                    yield self.collate(batch)
                    batch = []

                    if self.n_examples is not None and example_idx >= self.n_examples:
                        rank0_print(f'Finished generating {example_idx} examples on {self.split} split')
                        done = True
                        break

            if self.num_processes == 1 and batch != []: # flush for eval, sampling
                yield self.collate(batch)
                batch = []

            epoch_idx += 1
            if self.n_epochs is not None and epoch_idx >= self.n_epochs:
                done = True
                break

    def get_num_training_steps(self):
        max_prompt_count = min(float("inf"), self.max_prompt_count) if self.max_prompt_count else float("inf")
        num_pairs = int(sum(min(max_prompt_count, len(example.pairs)) for _, example in self.full_data.items()))
        num_training_steps = num_pairs * self.kwargs.get('frac_unique_desirable', 1.0) + num_pairs * self.kwargs.get('frac_unique_undesirable', 1.0)
        return num_training_steps // self.num_processes


class ScoreDataLoader(UnpairedPreferenceDataLoader):
    def get_flat_data(self, prompts):
        """
        Return a flat list of examples given a list of prompts that index self.full_data.
        Assumes that there are a list of scores.
        """
        flat_data = []
        prev_status = 'rejected'

        for prompt in prompts:
            example = self.full_data[prompt]

            if self.max_prompt_count:
                example.pairs = self.rng.sample(example.pairs, min(self.max_prompt_count, len(example.pairs)))

            # for oasst, lower scores are better, so rank 0 is the best response and rank n is the worst
            if prev_status == 'rejected':
                flat_data.append((example, example.generations[np.argmin(example.scores)], 'chosen'))
            else:
                flat_data.append((example, example.generations[np.argmax(example.scores)], 'rejected'))

            prev_status = flat_data[-1][-1]

        return flat_data


class HalfPrefDataLoader(UnpairedPreferenceDataLoader):
    """
    Dataloader for training on only one output per input.
    This throws out at least half the data (more than half if there are multiple pairs per input).
    For this reason, this should ONLY be used for training.
    """
    def get_flat_data(self, prompts):
        """
        Return a flat list of examples given a list of prompts that index self.full_data.
        Only use one preference pair per input.
        """
        flat_data = []
        prev_status = 'rejected'

        for prompt in prompts:
            example = self.full_data[prompt]

            if self.max_prompt_count:
                example.pairs = self.rng.sample(example.pairs, min(self.max_prompt_count, len(example.pairs)))

            for i,j in example.pairs:
                if prev_status == 'rejected':
                    flat_data.append((example, example.generations[i], 'chosen'))
                else:
                    flat_data.append((example, example.generations[j], 'rejected'))

                prev_status = flat_data[-1][-1]
                break # only use one pair

        return flat_data


class PairedPreferenceDataLoader(DataLoader):
    """
    Dataloader for losses that do require pairwise preferences (e.g., DPO).
    """
    def __iter__(self):
        prompts = list(self.full_data.keys())
        flat_data = []

        for prompt in prompts:
            example = self.full_data[prompt]

            if self.max_prompt_count:
                example.pairs = self.rng.sample(example.pairs, min(self.max_prompt_count, len(example.pairs)))

            for pair in example.pairs:
                flat_data.append((example, pair))

        if self.num_processes == 1: # for eval, sampling
            usable_size = len(flat_data)
        else: # to avoid hanging with uneven batches
            global_batch_size = int(self.num_processes * self.microbatch_size)
            usable_size = len(flat_data) // global_batch_size * global_batch_size

        self.rng.shuffle(flat_data) # shuffle before splitting across processes, otherwise some processes will only get chosen examples
        flat_data = [d for i, d in enumerate(flat_data[:usable_size]) if i % self.num_processes == self.process_index]
         
        epoch_idx = 0
        example_idx = 0
        done = False

        while True:
            if done: break
            self.rng.shuffle(flat_data)
            batch = []

            for example, (i, j) in flat_data:
                batch_element = {}
                batch_element.update(self.tokenize_batch_element(example.prompt, example.generations[i], example.truncation_mode, prefix='chosen'))
                batch_element.update(self.tokenize_batch_element(example.prompt, example.generations[j], example.truncation_mode, prefix='rejected'))
                batch.append(batch_element)

                if len(batch) >= self.microbatch_size:
                    example_idx += len(batch) * self.num_processes
                    yield self.collate(batch)
                    batch = []

                    if self.n_examples is not None and example_idx >= self.n_examples:
                        rank0_print(f'Finished {example_idx} examples on {self.split} split')
                        done = True
                        break

            if self.num_processes == 1 and batch != []: # flush for eval, sampling
                yield self.collate(batch)
                batch = []

            epoch_idx += 1
            if self.n_epochs is not None and epoch_idx >= self.n_epochs:
                done = True
                break

    def get_num_training_steps(self):
        max_prompt_count = min(float("inf"), self.max_prompt_count) if self.max_prompt_count else float("inf")
        all_data = int(sum(min(max_prompt_count, len(example.pairs)) for _, example in self.full_data.items()))
        return all_data // self.num_processes
